// Import the ioredis library
const IORedis = require("ioredis");

// Create a new Redis client
const messageClient = new IORedis({
  // Provide Redis server host, port, and password from environment variables
  host: process.env.REDIS_HOST,
  port: process.env.REDIS_PORT,
  password: process.env.REDIS_PASSWORD,
  
  // Setup a retry strategy for reconnecting to the Redis server if the connection is lost
  // The delay for each retry attempt increases linearly (times * 50) but is capped at 2000 milliseconds
  retryStrategy: function (times) {
    const delay = Math.min(times * 50, 2000);
    return delay;
  },
});

// Set up an error event listener on the Redis client to log any errors
messageClient.on("error", (err) => {
  console.log("Error", err);
});

// The data structure for messages stored in Redis includes the following fields:
// id - Automatically generated by Redis
// sender - The sender of the message
// text - The content of the message
// timestamp - The time when the message was sent

// Export the Redis client for use in other parts of the application
module.exports = messageClient;
